#! /usr/bin/env bash

# Shows the output of every command
set +x

rebuild_home_thinkpad() {
  nix build .#homeConfigurations.oscar.activationPackage
  result/activate -b
}

rebuild_home_dell() {
  nix build .#homeConfigurations.oscar-dell.activationPackage
  result/activate -b
}

rebuild_system() {
  # nix build .#nixosConfigurations.tongfang-amd.config.system.build.toplevel
  # sudo result/bin/switch-to-configuration switch
  sudo nixos-rebuild switch --flake .#thinkpad
}

switch_system() {
  echo "switch to most recent system config in ./result/bin/..."
  sudo result/bin/switch-to-configuration switch
}

switch_home() {
  echo "switch to most recent home config"
  rm /home/oscar/.xmonad/xmonad-x86_64-linux
  result/bin/home-manager-generation switch
}

rebuild_vm() {
  sudo nixos-rebuild build-vm --flake .#thinkpad
}

restart_X() {
  echo "⚠️ Restarting X11 (requires authentication) ⚠️"
  systemctl restart display-manager
}

case $1 in
  "thinkpad")
    rebuild_home_thinkpad;;
  "dell")
    rebuild_home_dell;;
  "system")
    switch_system;;
  "home")
    switch_home;;    
  "restart-x")
    restart_X;;
  "update-zsh")
    zsh -c zsh_update_completions;;
#  "vm")
#    rebuild_vm;;
  *)
    echo "expected 'thinkpad', 'system', 'home', 'restart-x', 'update-zsh'";;
esac
